# Generated by Django 6.0.1 on 2026-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Código de Reset de Contraseña',
                'verbose_name_plural': 'Códigos de Reset de Contraseña',
            },
        ),
    ]
