# Generated by Django 6.0.1 on 2026-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_codigoresetpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('registro', 'Registro administrador'), ('reset', 'Reset de contraseña')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Código de Verificación',
                'verbose_name_plural': 'Códigos de Verificación',
            },
        ),
        migrations.DeleteModel(
            name='CodigoRegistroAdmin',
        ),
        migrations.DeleteModel(
            name='CodigoResetPassword',
        ),
        migrations.AddIndex(
            model_name='codigoverificacion',
            index=models.Index(fields=['correo', 'tipo', 'usado'], name='panel_codig_correo_3473b8_idx'),
        ),
    ]
