# Generated by Django 6.0.1 on 2026-02-22 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paradas', models.ManyToManyField(to='principal.parada')),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField()),
                ('bidireccional', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='principal.parada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='principal.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ruta')),
            ],
        ),
    ]
